# Generated by Django 6.0.3 on 2026-03-12 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nazwa')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nazwa')),
                ('unit', models.CharField(choices=[('szt', 'sztuki'), ('g', 'gramy'), ('kg', 'kilogramy'), ('ml', 'mililitry'), ('l', 'litry'), ('łyżka', 'łyżki'), ('łyżeczka', 'łyżeczki'), ('szklanka', 'szklanki'), ('szczypta', 'szczypty'), ('plaster', 'plastry'), ('ząbek', 'ząbki')], default='szt', max_length=20, verbose_name='jednostka')),
            ],
            options={
                'verbose_name': 'składnik',
                'verbose_name_plural': 'składniki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='opis')),
                ('instructions', models.TextField(verbose_name='instrukcje przygotowania')),
                ('prep_time', models.PositiveIntegerField(verbose_name='czas przygotowania (min)')),
                ('difficulty', models.CharField(choices=[('easy', 'Łatwy'), ('medium', 'Średni'), ('hard', 'Trudny')], default='medium', max_length=10, verbose_name='poziom trudności')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='zdjęcie')),
                ('is_published', models.BooleanField(default=True, verbose_name='opublikowany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data modyfikacji')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category', verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'przepis',
                'verbose_name_plural': 'przepisy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ilość')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient', verbose_name='składnik')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='przepis')),
            ],
            options={
                'verbose_name': 'składnik przepisu',
                'verbose_name_plural': 'składniki przepisu',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='składniki'),
        ),
    ]
