# Generated by Django 6.0.3 on 2026-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary_preferences',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='accounts.dietarypreference', verbose_name='preferencje dietetyczne'),
        ),
    ]
