# Generated by Django 6.0.3 on 2026-03-12 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='treść')),
                ('rating', models.IntegerField(help_text='Ocena od 1 do 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ocena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe', verbose_name='przepis')),
            ],
            options={
                'verbose_name': 'komentarz',
                'verbose_name_plural': 'komentarze',
                'ordering': ['-created_at'],
            },
        ),
    ]
